In [4]:
import pandas as pd

In [ ]:
#reading the csv file into a pandas dataframe
df = pd.read_csv("UIC Police Daily Crime-Fire Log 07 Sep 26.csv")
df

,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD\nReport #,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Crime / Fire Incidents\nThe purpose of the dai...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Criminal Damage to Government Supported Proper...,1740 W. Taylor St/ UIC Hospital – Floor 8 East...,07 Sep 26 /\n06:16 pm,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337,NaN
4,Possession of a Controlled Substance,1740 W. Taylor St/ UIC Hospital – Floor 5 East...,07 Sep 26 /\n11:09 pm,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,NaN
5,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD\nReport #,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Non-Criminal Incidents\nIncidents reported in ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Lost Article,851 S. Morgan St/ Science & Engineering Office...,07 Sep 26 /\n01:41 pm,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334,NaN
10,Information,1740 W. Taylor St/ UIC Hospital – Main Entranc...,07 Sep 26 /\n01:37 pm,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335,NaN
11,Information,940 W. Harrison St/ Academic & Residential Com...,07 Sep 26 /\n03:32 pm,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336,NaN

In [ ]:
#dropping the last column of the dataframe since it is empty
df = df.drop(columns=df.columns[7]) 
df

,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD\nReport #
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Crime / Fire Incidents\nThe purpose of the dai...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Criminal Damage to Government Supported Proper...,1740 W. Taylor St/ UIC Hospital – Floor 8 East...,07 Sep 26 /\n06:16 pm,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337
4,Possession of a Controlled Substance,1740 W. Taylor St/ UIC Hospital – Floor 5 East...,07 Sep 26 /\n11:09 pm,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338
5,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD\nReport #
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Non-Criminal Incidents\nIncidents reported in ...,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Lost Article,851 S. Morgan St/ Science & Engineering Office...,07 Sep 26 /\n01:41 pm,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334
10,Information,1740 W. Taylor St/ UIC Hospital – Main Entranc...,07 Sep 26 /\n01:37 pm,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335
11,Information,940 W. Harrison St/ Academic & Residential Com...,07 Sep 26 /\n03:32 pm,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336

In [ ]:
#renaming the column 'UICPD\nReport #' to 'UICPD Report Number' for better readability
df = df.rename({'UICPD\nReport #':'UICPD Report Number'}, axis=1)
df

,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Crime / Fire Incidents\nThe purpose of the dai...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Criminal Damage to Government Supported Proper...,1740 W. Taylor St/ UIC Hospital – Floor 8 East...,07 Sep 26 /\n06:16 pm,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337
4,Possession of a Controlled Substance,1740 W. Taylor St/ UIC Hospital – Floor 5 East...,07 Sep 26 /\n11:09 pm,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338
5,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD\nReport #
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Non-Criminal Incidents\nIncidents reported in ...,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Lost Article,851 S. Morgan St/ Science & Engineering Office...,07 Sep 26 /\n01:41 pm,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334
10,Information,1740 W. Taylor St/ UIC Hospital – Main Entranc...,07 Sep 26 /\n01:37 pm,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335
11,Information,940 W. Harrison St/ Academic & Residential Com...,07 Sep 26 /\n03:32 pm,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336

In [9]:
#splitting the dataframe into two separate dataframes, one for criminal incidents and one for non-criminal incidents
split_num = df[df['Incident'].str.startswith('Non-Criminal Incidents')].index[0]
split_num

7

In [10]:
#creating a new dataframe for criminal incidents
df_crime = df.iloc[:split_num]
df_crime

,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Crime / Fire Incidents\nThe purpose of the dai...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Criminal Damage to Government Supported Proper...,1740 W. Taylor St/ UIC Hospital – Floor 8 East...,07 Sep 26 /\n06:16 pm,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337
4,Possession of a Controlled Substance,1740 W. Taylor St/ UIC Hospital – Floor 5 East...,07 Sep 26 /\n11:09 pm,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338
5,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD\nReport #
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#dropping the first three rows and the last two rows from the criminal incidents dataframe
#doing this because these rows were NA values that separated the 2 tables and not used for any data information
df_crime = df_crime.drop([0, 1, 2]) 
df_crime = df_crime.drop(df_crime.tail(2).index)  
df_crime

,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number
3,Criminal Damage to Government Supported Proper...,1740 W. Taylor St/ UIC Hospital – Floor 8 East...,07 Sep 26 /\n06:16 pm,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337
4,Possession of a Controlled Substance,1740 W. Taylor St/ UIC Hospital – Floor 5 East...,07 Sep 26 /\n11:09 pm,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338

In [ ]:
#adding a new column to the criminal incidents dataframe called 'Incident Type' and setting all values to 'Criminal/Fire'
df_crime['Incident Type'] = "Criminal/Fire" 
df_crime

,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type
3,Criminal Damage to Government Supported Proper...,1740 W. Taylor St/ UIC Hospital – Floor 8 East...,07 Sep 26 /\n06:16 pm,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire
4,Possession of a Controlled Substance,1740 W. Taylor St/ UIC Hospital – Floor 5 East...,07 Sep 26 /\n11:09 pm,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire

In [13]:
#creating a new dataframe for non-criminal incidents
df_not_crime = df.iloc[split_num:]
df_not_crime

,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number
7,Non-Criminal Incidents\nIncidents reported in ...,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Lost Article,851 S. Morgan St/ Science & Engineering Office...,07 Sep 26 /\n01:41 pm,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334
10,Information,1740 W. Taylor St/ UIC Hospital – Main Entranc...,07 Sep 26 /\n01:37 pm,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335
11,Information,940 W. Harrison St/ Academic & Residential Com...,07 Sep 26 /\n03:32 pm,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336

In [14]:
#repeating dropping the NA rows for the non-criminal incidents dataframe
df_not_crime = df_not_crime.drop(df_not_crime.head(2).index) # drop first 2 rows 
df_not_crime

,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number
9,Lost Article,851 S. Morgan St/ Science & Engineering Office...,07 Sep 26 /\n01:41 pm,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334
10,Information,1740 W. Taylor St/ UIC Hospital – Main Entranc...,07 Sep 26 /\n01:37 pm,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335
11,Information,940 W. Harrison St/ Academic & Residential Com...,07 Sep 26 /\n03:32 pm,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336

In [ ]:
#repeating adding a incident type column and labeling as non-criminal
df_not_crime['Incident Type'] = 'Non-Criminal'
df_not_crime

,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type
9,Lost Article,851 S. Morgan St/ Science & Engineering Office...,07 Sep 26 /\n01:41 pm,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal
10,Information,1740 W. Taylor St/ UIC Hospital – Main Entranc...,07 Sep 26 /\n01:37 pm,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal
11,Information,940 W. Harrison St/ Academic & Residential Com...,07 Sep 26 /\n03:32 pm,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal

In [ ]:
#combining the two dataframes into one
df_combine = pd.concat([df_crime, df_not_crime])
df_combine

,Incident,Location / Bldg #,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type
3,Criminal Damage to Government Supported Proper...,1740 W. Taylor St/ UIC Hospital – Floor 8 East...,07 Sep 26 /\n06:16 pm,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire
4,Possession of a Controlled Substance,1740 W. Taylor St/ UIC Hospital – Floor 5 East...,07 Sep 26 /\n11:09 pm,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire
9,Lost Article,851 S. Morgan St/ Science & Engineering Office...,07 Sep 26 /\n01:41 pm,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal
10,Information,1740 W. Taylor St/ UIC Hospital – Main Entranc...,07 Sep 26 /\n01:37 pm,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal
11,Information,940 W. Harrison St/ Academic & Residential Com...,07 Sep 26 /\n03:32 pm,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal

In [ ]:
#splitting the 'Location / Bldg #' column into three separate columns: 'Location', 'Building', and 'Building Number'
df_combine[['Location', 'Building', 'Building Number']] = df_combine['Location / Bldg #'].str.split('/', expand=True)
df_combine = df_combine.drop('Location / Bldg #', axis=1)
df_combine

,Incident,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type,Location,Building,Building Number
3,Criminal Damage to Government Supported Proper...,07 Sep 26 /\n06:16 pm,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 8 East,\n949 Building
4,Possession of a Controlled Substance,07 Sep 26 /\n11:09 pm,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 5 East,\n949 Building
9,Lost Article,07 Sep 26 /\n01:41 pm,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal,851 S. Morgan St,Science & Engineering Offices,\n631 Building
10,Information,07 Sep 26 /\n01:37 pm,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal,1740 W. Taylor St,UIC Hospital – Main Entrance,949 Building
11,Information,07 Sep 26 /\n03:32 pm,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal,940 W. Harrison St,Academic & Residential Complex,\n640 Building

In [ ]:
#cleaning column names for better readability
df_combine['Building Number'] = df_combine['Building Number'].str.replace('Building', '')
df_combine['Building Number'] = df_combine['Building Number'].str.replace('\n', '')
df_combine

,Incident,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type,Location,Building,Building Number
3,Criminal Damage to Government Supported Proper...,07 Sep 26 /\n06:16 pm,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 8 East,949
4,Possession of a Controlled Substance,07 Sep 26 /\n11:09 pm,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 5 East,949
9,Lost Article,07 Sep 26 /\n01:41 pm,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal,851 S. Morgan St,Science & Engineering Offices,631
10,Information,07 Sep 26 /\n01:37 pm,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal,1740 W. Taylor St,UIC Hospital – Main Entrance,949
11,Information,07 Sep 26 /\n03:32 pm,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal,940 W. Harrison St,Academic & Residential Complex,640

In [ ]:
#cleaning the 'Date/Time Reported' column to remove any newline characters
df_combine['Date/Time Reported'] = df_combine['Date/Time Reported'].str.replace('/\n', '')
df_combine

,Incident,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type,Location,Building,Building Number
3,Criminal Damage to Government Supported Proper...,07 Sep 26 06:16 pm,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 8 East,949
4,Possession of a Controlled Substance,07 Sep 26 11:09 pm,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 5 East,949
9,Lost Article,07 Sep 26 01:41 pm,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal,851 S. Morgan St,Science & Engineering Offices,631
10,Information,07 Sep 26 01:37 pm,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal,1740 W. Taylor St,UIC Hospital – Main Entrance,949
11,Information,07 Sep 26 03:32 pm,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal,940 W. Harrison St,Academic & Residential Complex,640

In [ ]:
#converting the date in reported column to number only format
df_combine['Date/Time Reported'] = pd.to_datetime(df_combine['Date/Time Reported'], format='%d %b %y %I:%M %p')
df_combine

,Incident,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type,Location,Building,Building Number
3,Criminal Damage to Government Supported Proper...,2026-09-07 18:16:00,07 Sep 26 /\n05:55 pm -\n06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 8 East,949
4,Possession of a Controlled Substance,2026-09-07 23:09:00,07 Sep 26 /\n10:53 pm -\n10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 5 East,949
9,Lost Article,2026-09-07 13:41:00,06 Sep 26 /\n08:00 pm -\n09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal,851 S. Morgan St,Science & Engineering Offices,631
10,Information,2026-09-07 13:37:00,07 Sep 26 /\n12:20 pm -\n01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal,1740 W. Taylor St,UIC Hospital – Main Entrance,949
11,Information,2026-09-07 15:32:00,07 Sep 26 /\n12:40 am -\n02:20 pm,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal,940 W. Harrison St,Academic & Residential Complex,640

In [21]:
#cleaning the 'Date/Time Occurred' column to remove any newline characters
df_combine['Date/Time Occurred'] = df_combine['Date/Time Occurred'].str.replace('/\n', '')
df_combine['Date/Time Occurred'] = df_combine['Date/Time Occurred'].str.replace('\n', '')
df_combine

,Incident,Date/Time Reported,Date/Time Occurred,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type,Location,Building,Building Number
3,Criminal Damage to Government Supported Proper...,2026-09-07 18:16:00,07 Sep 26 05:55 pm -06:15 pm,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 8 East,949
4,Possession of a Controlled Substance,2026-09-07 23:09:00,07 Sep 26 10:53 pm -10:55 pm,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 5 East,949
9,Lost Article,2026-09-07 13:41:00,06 Sep 26 08:00 pm -09:00 pm,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal,851 S. Morgan St,Science & Engineering Offices,631
10,Information,2026-09-07 13:37:00,07 Sep 26 12:20 pm -01:17 pm,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal,1740 W. Taylor St,UIC Hospital – Main Entrance,949
11,Information,2026-09-07 15:32:00,07 Sep 26 12:40 am -02:20 pm,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal,940 W. Harrison St,Academic & Residential Complex,640

In [ ]:
#splitting the occured column into start and end columns to compare end time with repoted time later
df_combine[['Date/Time Occurred Start', 'Date/Time Occurred End']] = df_combine['Date/Time Occurred'].str.split('-', expand=True)
df_combine = df_combine.drop('Date/Time Occurred', axis=1)
df_combine

,Incident,Date/Time Reported,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type,Location,Building,Building Number,Date/Time Occurred Start,Date/Time Occurred End
3,Criminal Damage to Government Supported Proper...,2026-09-07 18:16:00,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 8 East,949,07 Sep 26 05:55 pm,06:15 pm
4,Possession of a Controlled Substance,2026-09-07 23:09:00,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 5 East,949,07 Sep 26 10:53 pm,10:55 pm
9,Lost Article,2026-09-07 13:41:00,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal,851 S. Morgan St,Science & Engineering Offices,631,06 Sep 26 08:00 pm,09:00 pm
10,Information,2026-09-07 13:37:00,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal,1740 W. Taylor St,UIC Hospital – Main Entrance,949,07 Sep 26 12:20 pm,01:17 pm
11,Information,2026-09-07 15:32:00,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal,940 W. Harrison St,Academic & Residential Complex,640,07 Sep 26 12:40 am,02:20 pm

In [ ]:
#adding the date to the end column

df_combine['Date/Time Occurred End'] = df_combine['Date/Time Occurred Start'].apply(lambda x : ' '.join(x.split()[:3])) + ' ' + df_combine['Date/Time Occurred End']
df_combine

,Incident,Date/Time Reported,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type,Location,Building,Building Number,Date/Time Occurred Start,Date/Time Occurred End
3,Criminal Damage to Government Supported Proper...,2026-09-07 18:16:00,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 8 East,949,07 Sep 26 05:55 pm,07 Sep 26 06:15 pm
4,Possession of a Controlled Substance,2026-09-07 23:09:00,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 5 East,949,07 Sep 26 10:53 pm,07 Sep 26 10:55 pm
9,Lost Article,2026-09-07 13:41:00,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal,851 S. Morgan St,Science & Engineering Offices,631,06 Sep 26 08:00 pm,06 Sep 26 09:00 pm
10,Information,2026-09-07 13:37:00,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal,1740 W. Taylor St,UIC Hospital – Main Entrance,949,07 Sep 26 12:20 pm,07 Sep 26 01:17 pm
11,Information,2026-09-07 15:32:00,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal,940 W. Harrison St,Academic & Residential Complex,640,07 Sep 26 12:40 am,07 Sep 26 02:20 pm

In [ ]:
#converting the start and end columns to datetime format 
df_combine['Date/Time Occurred Start'] = pd.to_datetime(df_combine['Date/Time Occurred Start'], format='mixed')
df_combine['Date/Time Occurred End'] = pd.to_datetime(df_combine['Date/Time Occurred End'], format='mixed')
df_combine

,Incident,Date/Time Reported,Comments / Nature of Fire,Disposition,UICPD Report Number,Incident Type,Location,Building,Building Number,Date/Time Occurred Start,Date/Time Occurred End
3,Criminal Damage to Government Supported Proper...,2026-09-07 18:16:00,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 8 East,949,2026-09-07 17:55:00,2026-09-07 18:15:00
4,Possession of a Controlled Substance,2026-09-07 23:09:00,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 5 East,949,2026-09-07 22:53:00,2026-09-07 22:55:00
9,Lost Article,2026-09-07 13:41:00,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal,851 S. Morgan St,Science & Engineering Offices,631,2026-09-06 20:00:00,2026-09-06 21:00:00
10,Information,2026-09-07 13:37:00,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal,1740 W. Taylor St,UIC Hospital – Main Entrance,949,2026-09-07 12:20:00,2026-09-07 13:17:00
11,Information,2026-09-07 15:32:00,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal,940 W. Harrison St,Academic & Residential Complex,640,2026-09-07 00:40:00,2026-09-07 14:20:00

In [ ]:
#rnaming the comments column to something shorter
df_combine = df_combine.rename({'Comments / Nature of Fire':'Comments'}, axis=1)
df_combine

,Incident,Date/Time Reported,Comments,Disposition,UICPD Report Number,Incident Type,Location,Building,Building Number,Date/Time Occurred Start,Date/Time Occurred End
3,Criminal Damage to Government Supported Proper...,2026-09-07 18:16:00,A UIC employee reported that two separate pati...,In Progress,26-01337,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 8 East,949,2026-09-07 17:55:00,2026-09-07 18:15:00
4,Possession of a Controlled Substance,2026-09-07 23:09:00,A UIC employee found a patient in possession o...,Cleared / Closed Exc-Other EXC,26-01338,Criminal/Fire,1740 W. Taylor St,UIC Hospital – Floor 5 East,949,2026-09-07 22:53:00,2026-09-07 22:55:00
9,Lost Article,2026-09-07 13:41:00,A UIC student reported they lost their persona...,Closed,26-01334,Non-Criminal,851 S. Morgan St,Science & Engineering Offices,631,2026-09-06 20:00:00,2026-09-06 21:00:00
10,Information,2026-09-07 13:37:00,A non UIC affiliate reported that their ID car...,Closed,26-01335,Non-Criminal,1740 W. Taylor St,UIC Hospital – Main Entrance,949,2026-09-07 12:20:00,2026-09-07 13:17:00
11,Information,2026-09-07 15:32:00,A UIC student reported that another student kn...,Closed,26-01336,Non-Criminal,940 W. Harrison St,Academic & Residential Complex,640,2026-09-07 00:40:00,2026-09-07 14:20:00